### ISSUE TITLE
1.15 duyu

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/duyu#1]
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
--输出文件  ouput.dat
100000087010000|20171226|2017122611453810|8031.76|6
TX41|20171226093224|FB20171220213224BBO118514|BANK|50|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225162900|FB20171225162900BBO119003|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225164412|FB20171225164412BBO119004|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171226103846|FB20171225173836BBO119017|BANK|100|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225185646|FB20171225185646BBO119023|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225190536|FB20171225190536BBO119024|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040

--输入文件  input.dat
100000087010000|20171226000000|100000087010000_D2017122611453810_20171226000000|0.00|0|0.00|0|0.00|0
TX41|FB20171220213224BBO118514|50.00|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225162900BBO119003|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225164412BBO119004|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225173836BBO119017|100.00|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225185646BBO119023|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225190536BBO119024|1970.44|03040000|6230209874563882|201711221725306040|null|9

"""
import re

ouput_title = ''
ouput_lines = []

with open('input.dat', 'r') as f: 
    title_line = f.readline()  # 读第一行
    title_segments = title_line.split('|')
    title_seg1 = title_segments[0] # 100000087010000
    # 接下来 输出那边需要的这两个字段 20171226|2017122611453810
    # 用正则从100000087010000_D2017122611453810_20171226000000里面提取
    title_seg2_3_search = re.search('D\d+', title_segments[2]).group(0) # 这里结果是D2017122611453810
    title_seg3_timestamp = title_seg2_3_search[1:]
    title_seg2_date = title_seg3_timestamp[:6]
    title_seg4_total_money = 0  # 8031.76|6 这两个字段从输入那边累加过来的
    title_seg5_count = 0

    while True:                           
        line = f.readline()
        if 
        print line
        """ TX41|FB20171220213224BBO118514|50.00|03040000|6230209874563882|201711221725306040|null|9 """
        if line:
            
            segments = line.split('|')
            # 假设需要100000087010000、2018010419074879、80.0、FB20180104124319BBO119190这四个字段
            seg1_tx41 = segments[0]
            seg2_timestamp = title_seg3_timestamp[:-2] # '20171225162900' 
            # 输出这边的 20171225162900 我看不出是哪来的。标题那边title_seg3_timestamp是16位，这里是14位，先这样暂且用着吧
            seg3_fb = segments[1]
            seg4_bank = 'BANK'
            seg5_money = segments[2]
            title_seg4_total_money += float(seg5_money)
            title_seg5_count += 1
            seg6 = segments[3]
            seg7 = segments[4]
            seg8 = '1'
            seg9 = '441402199202245603' # 输出这边的 441402199202245603 我看不出是哪来的
            seg10 = segments[5]
            # ouput_lines.append('|'.join([seg1_tx41, seg2_timestamp, seg3_fb, seg4_bank, seg5_money, seg6, seg7, seg8, seg9, seg10]))

    print ouput_lines, title_seg4_total_money, title_seg5_count

**Comment by vieyahn2017** [comment]
能跟帖吗

**Comment by duli1985** [comment]
#coding:utf-8
import requests
from config import config
import paramiko
import re
import os
import sys

#服务器信息，主机名（IP地址）、端口号、用户名及密码
hostname = config.file_interfaceHost
port = config.file_interfacePort
username = config.file_userName
password = config.file_pwd

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname, port, username, password , compress=True)
sftp_client = client.open_sftp()
upLoadfileD = sftp_client.open("/opt/file/fund-gw/share-dir/export/settle/fundout/generate/20180108/100000087010000_D2018010817532924_20180107000000_gbk.txt")#文件路径
downLoadfileD = sftp_client.open("/opt/file/fund-gw/share-dir/export/settle/fundout/generate/20180108/100000087010000_D2018010817532924_20180107000000_back.txt")


with open("upLoadfileD" , 'r') as upfD:
    title_line = upfD.readline() #读首行
    title_segments = title_line.split('|')
    title_seg1_orgNo = title_segments[0] #机构号100000087010000
    title_seg2_reqNo = title_segments[1] #发起时间
    title_seg3_batchNum = title_segments[2] #批次号

    while True:
        line = upfD.readline()
        print line
            #判断是否为空
            # if line:
            #     segmnets = line.split('|')
            #     #需要取出100000087010000，FB20171220213224BBO118514，50，03040000，6230209874563882，201711221725306040
            #     seg1_orgNum = segmnets[0] #机构号
            #     seg2_reqDate = segmnets[1] #发起日期
            #     seg3_batchNum = segmnets[2] #批次号
            #     print(seg1_orgNum,seg2_reqDate,seg3_batchNum)





'''
--原始文件
100000087010000|20171226|2017122611453810|8031.76|6
TX41|20171226093224|FB20171220213224BBO118514|BANK|50|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225162900|FB20171225162900BBO119003|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225164412|FB20171225164412BBO119004|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171226103846|FB20171225173836BBO119017|BANK|100|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225185646|FB20171225185646BBO119023|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225190536|FB20171225190536BBO119024|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040

--处理后文件
100000087010000|20171226000000|100000087010000_D2017122611453810_20171226000000|0.00|0|0.00|0|0.00|0
TX41|FB20171220213224BBO118514|50.00|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225162900BBO119003|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225164412BBO119004|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225173836BBO119017|100.00|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225185646BBO119023|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225190536BBO119024|1970.44|03040000|6230209874563882|201711221725306040|null|9

**Comment by vieyahn2017** [comment]
```python
sftp_client = client.open_sftp()
upLoadfileD = sftp_client.open("/opt/file/fund-gw/share-dir/export/settle/fundout/generate/20180108/100000087010000_D2018010817532924_20180107000000_gbk.txt")#文件路径
downLoadfileD = sftp_client.open("/opt/file/fund-gw/share-dir/export/settle/fundout/generate/20180108/100000087010000_D2018010817532924_20180107000000_back.txt")

```

这段代码已经打开一个upLoadfileD 了，不再需要用with那样open
，
我那边是用本地文件测试，肯定跟你的代码还是不同

**Comment by vieyahn2017** [comment]
、你看看这个
https://github.com/vergili/PythonExamples/blob/deeacadfb85feead212ad870e076bc78c7b2bcad/sftp_get.py

**Comment by vieyahn2017** [comment]
本地文件的代码实现
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
--upLoadfileD 输入文件  我本地测试名字input.txt
--upLoadfileD = sftp_client.open("/opt/file/fund-gw/share-dir/export/settle/fundout/generate/20180108/100000087010000_D2018010817532924_20180107000000_gbk.txt")#文件路径
100000087010000|20171226|2017122611453810|8031.76|6
TX41|20171226093224|FB20171220213224BBO118514|BANK|50|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225162900|FB20171225162900BBO119003|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225164412|FB20171225164412BBO119004|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171226103846|FB20171225173836BBO119017|BANK|100|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225185646|FB20171225185646BBO119023|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040
TX41|20171225190536|FB20171225190536BBO119024|BANK|1970.44|03040000|6230209874563882|1|441402199202245603|201711221725306040

-- downLoadfileD 输出文件  我本地测试名字ouput.txt
--downLoadfileD = sftp_client.open("/opt/file/fund-gw/share-dir/export/settle/fundout/generate/20180108/100000087010000_D2018010817532924_20180107000000_back.txt")
基金销售机构号，发起日期，批次号，成功总金额
100000087010000|20171226000000|100000087010000_D2017122611453810_20171226000000|0.00|0|0.00|0|0.00|0
TX41|FB20171220213224BBO118514|50.00|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225162900BBO119003|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225164412BBO119004|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225173836BBO119017|100.00|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225185646BBO119023|1970.44|03040000|6230209874563882|201711221725306040|null|9
TX41|FB20171225190536BBO119024|1970.44|03040000|6230209874563882|201711221725306040|null|9
交易类型，基金销售机构交易流水号，交易金额，银行代码，银行卡号，银行交易流水号，交易执行时间，交易执行状态
"""
import re

ouput_title = [] #用文本数组，最后用|合并
ouput_lines = []

with open('input.txt', 'r') as f: 

    title_segments = []

    while True:
        line = f.readline()
        if not line:
            break
        if line.startswith('TX'):
            # 详细条目
            # TX41|20171226093224|FB20171220213224BBO118514|BANK|50|03040000|6230209874563882|1|441402199202245603|201711221725306040
            # 交易类型，基金销售机构交易流水号，通联交易流水号
            # 需要的几个字段是
            segs = line.strip().split('|')
            # 这是需要的几个字段
            seg0_tx41, seg2_fb, seg4_money, seg5_bank, seg6_bankcard, seg9 = segs[0], segs[2], segs[4], segs[5], segs[6], segs[9]
            # 构造目标文件的行
            result_line_list = []
            result_line_list.append(seg0_tx41) 
            result_line_list.append(seg2_fb) 
            result_line_list.append(seg4_money) 
            result_line_list.append(seg5_bank) 
            result_line_list.append(seg6_bankcard) 
            result_line_list.append(seg9) 
            result_line_list.append('null') # 交易执行时间 设为null
            result_line_list.append('9') # 交易执行状态 1 2 4 9 应该是根据源文件的某些来判断吧，这个规则看你怎么实现

            result_line_str = '|'.join(result_line_list)
            ouput_lines.append(result_line_str)
        else:
            # 标题行
            title_segments = line.split('|')

    # 构造标题行 
    # 100000087010000|20171226000000|100000087010000_D2017122611453810_20171226000000|0.00|0|0.00|0|0.00|0
    ouput_title.append(title_segments[0]) # 基金销售机构
    ouput_title.append(title_segments[1] + '000000')  # 20171226000000
    ouput_title.append('{0}_D{1}_{2}000000'.format(title_segments[0], title_segments[2], title_segments[1])) 

    # 后面的6个字段，你怎么处理 0.00|0|0.00|0|0.00|0
    ouput_title.append('0.00')
    ouput_title.append('0.')
    ouput_title.append('0.00')
    ouput_title.append('0.')
    ouput_title.append('0.00')
    ouput_title.append('0')


with open('ouput.txt', 'w') as f: 
    f.write('|'.join(ouput_title))
    f.write('\n')
    for line in ouput_lines:
        f.write(line)
        f.write('\n')

```

**Comment by vieyahn2017** [comment]
远程代码

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
from config import config
import paramiko
import re
import os
import sys

#服务器信息，主机名（IP地址）、端口号、用户名及密码
hostname = config.file_interfaceHost
port = config.file_interfacePort
username = config.file_userName
password = config.file_pwd

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname, port, username, password , compress=True)
sftp_client = client.open_sftp()
upLoadfileD = sftp_client.open("/opt/file/fund-gw/share-dir/export/settle/fundout/generate/20180108/100000087010000_D2018010817532924_20180107000000_gbk.txt")#文件路径
downLoadfileD = sftp_client.open("/opt/file/fund-gw/share-dir/export/settle/fundout/generate/20180108/100000087010000_D2018010817532924_20180107000000_back.txt")

ouput_title = [] #用文本数组，最后用|合并
ouput_lines = []
title_segments = []

for line in upLoadfileD:
    if line.startswith('TX'):
        # 详细条目
        # TX41|20171226093224|FB20171220213224BBO118514|BANK|50|03040000|6230209874563882|1|441402199202245603|201711221725306040
        # 交易类型，基金销售机构交易流水号，通联交易流水号
        # 需要的几个字段是
        segs = line.strip().split('|')
        # 这是需要的几个字段
        seg0_tx41, seg2_fb, seg4_money, seg5_bank, seg6_bankcard, seg9 = segs[0], segs[2], segs[4], segs[5], segs[6], segs[9]
        # 构造目标文件的行
        result_line_list = []
        result_line_list.append(seg0_tx41) 
        result_line_list.append(seg2_fb) 
        result_line_list.append(seg4_money) 
        result_line_list.append(seg5_bank) 
        result_line_list.append(seg6_bankcard) 
        result_line_list.append(seg9) 
        result_line_list.append('null') # 交易执行时间 设为null
        result_line_list.append('9') # 交易执行状态 1 2 4 9 应该是根据源文件的某些来判断吧，这个规则看你怎么实现

        result_line_str = '|'.join(result_line_list)
        ouput_lines.append(result_line_str)
    else:
        # 标题行
        title_segments = line.split('|')

# 构造标题行 
# 100000087010000|20171226000000|100000087010000_D2017122611453810_20171226000000|0.00|0|0.00|0|0.00|0
ouput_title.append(title_segments[0]) # 基金销售机构
ouput_title.append(title_segments[1] + '000000')  # 20171226000000
ouput_title.append('{0}_D{1}_{2}000000'.format(title_segments[0], title_segments[2], title_segments[1])) 

# 后面的6个字段，你怎么处理 0.00|0|0.00|0|0.00|0
ouput_title.append('0.00')
ouput_title.append('0.')
ouput_title.append('0.00')
ouput_title.append('0.')
ouput_title.append('0.00')
ouput_title.append('0')

print ouput_title
print ouput_lines

```

**Comment by vieyahn2017** [comment]
远程写文件，你要去测一下

```python
downLoadfileD.write('|'.join(ouput_title))
downLoadfileD.write('\n')
for line in ouput_lines:
    downLoadfileD.write(line)
    downLoadfileD.write('\n')

```

**Comment by duli1985** [comment]
OK

**Comment by vieyahn2017** [comment]
这一句
ouput_title.append('{0}_D{1}_{2}000000'.format(title_segments[0], title_segments[2], title_segments[1])) 
其中{0} {1} {2}的三个参数占位符号，用后面format方法的三个参数生成一个字符串

**Comment by duli1985** [comment]
嗯

**Comment by vieyahn2017** [comment]
'{0}D{1}{2}000000'.format(title_segments[0], title_segments[2], title_segments[1])
    
title_segments[0] 是 100000087010000    
title_segments[2] 是 20171226   
title_segments[1] 是 2017122611453810   
那一句生成100000087010000_D2017122611453810_20171226000000
