### ISSUE TITLE
o0118.py 正则替换日期和行数

### ISSUE THREAD

**Issue by vieyahn2017** [vieyahn2017/duyu#14]
正则替换日期和行数

**Comment by vieyahn2017** [comment]
你要处理的文件是
the_file_name = "201801080001.txt"

**Comment by vieyahn2017** [comment]
目前的代码是
https://github.com/vieyahn2017/duyu/blob/master/d20180117/o0118.py

**Comment by vieyahn2017** [comment]
你自己试试吧

**Comment by duli1985** [comment]
直接取128行的内容，怎么写？

**Comment by duli1985** [comment]
count = linecache.getline('C:/Users/likun/Desktop/autotest_file/OFD_02_379_20180104_04.TXT', 128)

**Comment by vieyahn2017** [comment]
如果只是取那么一行 把文件内容搞成一个数组
直接用数组就行，content[127]  （计数从0开始的）
但是你上面的代码是哪来的

另外那个文件是本地文件，还是sftp_client取的远程文件

**Comment by vieyahn2017** [comment]
另外刚刚的代码也是一种思路
```python
detail_order_lines_se = re.search(r"SHAREREGISTERDATE\n[\s\S]*\nOFDCFEND", content)

if detail_order_lines_se is not None:
    detail_order_lines = detail_order_lines_se.group().split('\n')
    order_counts = len(detail_order_lines) - 3 
    #去掉首行SHAREREGISTERDATE  第二行（记录条数） 尾行OFDCFEND
    order_counts_8_bits = str(order_counts).zfill(8) 
    content = re.sub(r"SHAREREGISTERDATE\n\d+\n", "SHAREREGISTERDATE\n%s\n" % order_counts_8_bits, content)

```

**Comment by vieyahn2017** [comment]
detail_order_lines是   
          从SHAREREGISTERDATE行 到 OFDCFEND行的数组   
detail_order_lines[2] 就是你要的128行，第一条交易数据行   
detail_order_lines[3]  第2条交易数据行
往后推~~~~~~~

**Comment by duli1985** [comment]
是本地文件
上面那行代码是我写的，取出128行的
第128行中，有10几处需要替换，我正在整理。一会儿贴出来你看看

**Comment by vieyahn2017** [comment]
你不要局限于128行需要替换，
而是说， 每一行详细的交易条目  有一些字段 需要替换

**Comment by vieyahn2017** [comment]
新帖代码 新开一个issue吧，这边已经很长了

**Comment by duli1985** [comment]
这个文件的格式是，行数不会变，所以128行才是重点啊

**Comment by vieyahn2017** [comment]
只管128这一行，  129 130也是交易记录，不管了？？？

**Comment by duli1985** [comment]
#!/usr/bin/python
#encoding: utf-8
import linecache
import re
import time

cfm_Order = 'C:/Users/likun/Desktop/autotest_file/OFD_02_379_20180104_04.TXT'
# #cfm_Order.read(932)

order_detail = linecache.getline(cfm_Order, 128)
print order_detail

new_detail = order_detail

#手工设置需要更改的内容
work_date = '65555555' #work_date：第5行，第128行的24-31位（[24-31])等
instOderNo = '541801030000000000237992' #申请订单号（仅针对用户发起交易），先手工设置，后期需要从订单表里取出：128行中的前24个字符串（order_detail[:23]）
cfm_count = '3333333333333333' #每笔确认份额，16位，两位小数，需手工设置：128行中的32到47个
cfm_amount = '4444444444444444' #每笔确认金额，16位，两位小数，需手工设置:128行中的48到63个

# detail_order_lines_se = re.search(r"SHAREREGISTERDATE\n[\s\S]*\nOFDCFEND", content)
#
# if detail_order_lines_se is not None:
#     detail_order_lines = detail_order_lines_se.group().split('\n')
#     order_counts = len(detail_order_lines) - 3
#     #去掉首行SHAREREGISTERDATE  第二行（记录条数） 尾行OFDCFEND
#     order_counts_8_bits = str(order_counts).zfill(8)
#     content = re.sub(r"SHAREREGISTERDATE\n\d+\n", "SHAREREGISTERDATE\n%s\n" % order_counts_8_bits, content)
if order_detail:
    new_detail1 = re.sub(order_detail[:23], instOderNo, order_detail)
    new_detail2 = re.sub(order_detail[24:31], work_date, order_detail)
    new_detail3 = re.sub(order_detail[35:50], cfm_count, order_detail)
    new_detail4 = re.sub(order_detail[51:66], cfm_amount, order_detail)
    print new_detail1, new_detail2, new_detail3, new_detail4

**Comment by duli1985** [comment]
假设只有一行，先把这一行改成需要的样子；再批量生成多行

**Comment by duli1985** [comment]
我那个部分替换有问题，只是给你看看，我想要做的是什么。

**Comment by vieyahn2017** [comment]
我也不知道你的对与错，不过及燃烧替换
肯定代码应该是
```python
if order_detail:
    order_detail = re.sub(order_detail[:23], instOderNo, order_detail)
    order_detail = re.sub(order_detail[24:31], work_date, order_detail)
    order_detail = re.sub(order_detail[35:50], cfm_count, order_detail)
    order_detail = re.sub(order_detail[51:66], cfm_amount, order_detail)

```

**Comment by vieyahn2017** [comment]
还有就是   
如果替换之前和替换以后，字符串长度不变，可以一直用下标那样取值   
如果长度变了，就要出错。

**Comment by duli1985** [comment]
如果替换之前和替换以后，字符串长度不变，可以一直用下标那样取值-----就是不能变，一个都不能错。我数的下标不对。

本来我也是这样写的， 但是替换有问题呀
if order_detail:
    order_detail = re.sub(order_detail[:23], instOderNo, order_detail)
    order_detail = re.sub(order_detail[24:31], work_date, order_detail)
    order_detail = re.sub(order_detail[35:50], cfm_count, order_detail)
    order_detail = re.sub(order_detail[51:66], cfm_amount, order_detail)
